name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request: {}

concurrency:
   group: ci-${{ github.head_ref || github.ref }}
   cancel-in-progress: true

jobs:
  lint:
    name: "Flake8"
    runs-on: ubuntu-latest

    steps:
      - name: Flake8
        run: flake8
